name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: erzez/reali-app:latest
  
  helm:
    runs-on: 'ubuntu-latest'
    needs: docker
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1.7.0'
      with:
        release: 'app-chart'
        namespace: 'default'
        chart: 'app'
        token: '${{ github.token }}'
        value-files: >-
          [
          "app-chart/values.yaml"
          ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
