name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: erzez/reali-app:latest
  
  helm:
    runs-on: 'ubuntu-latest'
    needs: docker
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.4.0
    
    - uses: peymanmortazavi/eks-helm-deploy@v2
      with:
        namespace: default        
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}        
        aws-region: us-east-1
        chart-path: app-chart
        cluster-name: extravagant-mushroom-1644660144.us-east-1.eksctl.io
        config-files: app-chart/values.yml
        name: app
